<?php

/**
 * sfSympalComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    thatsquality
 * @subpackage model
 * @author     ryan@thatsquality.com
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class sfSympalComment extends PluginsfSympalComment
{
}
