all:
  sympal_config:
    installed: true
    current_version: 1.0.0-ALPHA3
    sfSympalTqThemePlugin:
      installed: true
    sfSympalBlogPlugin:
      installed: true
    sfSympalCommentsPlugin:
      installed: true
    sfSympalTagsPlugin:
      installed: true
    i18n: true
    language_codes:
      - en
      - es
    upgrade_version_history:
      - 0.7.0__1
      - 0.7.0__2
      - 1.0.0_ALPHA4__1
      - 1.0.0_ALPHA4__2
      - 1.0.0_ALPHA4__3
      - 1.0.0_ALPHA4__4
