<?php

/**
 * sfSympalContentGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    thatsquality
 * @subpackage model
 * @author     ryan@thatsquality.com
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
class sfSympalContentGroup extends PluginsfSympalContentGroup
{
}
