<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addsfsympalsite extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('sf_sympal_site', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'theme' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'description' => 
             array(
              'type' => 'clob',
              'notnull' => true,
              'length' => NULL,
             ),
             'page_title' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'meta_keywords' => 
             array(
              'type' => 'string',
              'length' => 500,
             ),
             'meta_description' => 
             array(
              'type' => 'string',
              'length' => 500,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('sf_sympal_site');
    }
}