<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addsfsympalcontentlist extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('sf_sympal_content_list', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'content_type_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'rows_per_page' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'sort_column' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'sort_order' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'ASC',
              1 => 'DESC',
              ),
              'length' => NULL,
             ),
             'table_method' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'dql_query' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'content_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('sf_sympal_content_list');
    }
}