<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addsfsympalcomment extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('sf_sympal_comment', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'status' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'Pending',
              1 => 'Approved',
              2 => 'Denied',
              ),
              'default' => 'Pending',
              'notnull' => true,
              'length' => NULL,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'email_address' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'website' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'body' => 
             array(
              'type' => 'clob',
              'notnull' => true,
              'length' => NULL,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('sf_sympal_comment');
    }
}