<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addsfsympalcontentslot extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('sf_sympal_content_slot', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'is_column' => 
             array(
              'type' => 'boolean',
              'default' => 0,
              'length' => 25,
             ),
             'render_function' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'type' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'value' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             ), array(
             'indexes' => 
             array(
              'name' => 
              array(
              'fields' => 
              array(
               0 => 'name',
              ),
              ),
              'type' => 
              array(
              'fields' => 
              array(
               0 => 'type',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('sf_sympal_content_slot');
    }
}