<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfks extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('sf_guard_forgot_password', 'sf_guard_forgot_password_user_id_sf_guard_user_id', array(
             'name' => 'sf_guard_forgot_password_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_group_permission', 'sf_guard_group_permission_group_id_sf_guard_group_id', array(
             'name' => 'sf_guard_group_permission_group_id_sf_guard_group_id',
             'local' => 'group_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_group',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_group_permission', 'sf_guard_group_permission_permission_id_sf_guard_permission_id', array(
             'name' => 'sf_guard_group_permission_permission_id_sf_guard_permission_id',
             'local' => 'permission_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_permission',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_remember_key', 'sf_guard_remember_key_user_id_sf_guard_user_id', array(
             'name' => 'sf_guard_remember_key_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_user_group', 'sf_guard_user_group_user_id_sf_guard_user_id', array(
             'name' => 'sf_guard_user_group_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_user_group', 'sf_guard_user_group_group_id_sf_guard_group_id', array(
             'name' => 'sf_guard_user_group_group_id_sf_guard_group_id',
             'local' => 'group_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_group',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_user_permission', 'sf_guard_user_permission_user_id_sf_guard_user_id', array(
             'name' => 'sf_guard_user_permission_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_user_permission', 'sf_guard_user_permission_permission_id_sf_guard_permission_id', array(
             'name' => 'sf_guard_user_permission_permission_id_sf_guard_permission_id',
             'local' => 'permission_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_permission',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_blog_post', 'sf_sympal_blog_post_content_id_sf_sympal_content_id', array(
             'name' => 'sf_sympal_blog_post_content_id_sf_sympal_content_id',
             'local' => 'content_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_sympal_content',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_comment', 'sf_sympal_comment_user_id_sf_guard_user_id', array(
             'name' => 'sf_sympal_comment_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_content', 'sf_sympal_content_last_updated_by_id_sf_guard_user_id', array(
             'name' => 'sf_sympal_content_last_updated_by_id_sf_guard_user_id',
             'local' => 'last_updated_by_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => NULL,
             'onDelete' => 'SET NULL',
             ));
        $this->createForeignKey('sf_sympal_content', 'sf_sympal_content_created_by_id_sf_guard_user_id', array(
             'name' => 'sf_sympal_content_created_by_id_sf_guard_user_id',
             'local' => 'created_by_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => NULL,
             'onDelete' => 'SET NULL',
             ));
        $this->createForeignKey('sf_sympal_content', 'sf_sympal_content_site_id_sf_sympal_site_id', array(
             'name' => 'sf_sympal_content_site_id_sf_sympal_site_id',
             'local' => 'site_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_sympal_site',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_content', 'sf_sympal_content_content_type_id_sf_sympal_content_type_id', array(
             'name' => 'sf_sympal_content_content_type_id_sf_sympal_content_type_id',
             'local' => 'content_type_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_sympal_content_type',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_content_asset', 'sf_sympal_content_asset_content_id_sf_sympal_content_id', array(
             'name' => 'sf_sympal_content_asset_content_id_sf_sympal_content_id',
             'local' => 'content_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_sympal_content',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_content_asset', 'sf_sympal_content_asset_asset_id_sf_sympal_asset_id', array(
             'name' => 'sf_sympal_content_asset_asset_id_sf_sympal_asset_id',
             'local' => 'asset_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_sympal_asset',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_content_comment', 'sf_sympal_content_comment_content_id_sf_sympal_content_id', array(
             'name' => 'sf_sympal_content_comment_content_id_sf_sympal_content_id',
             'local' => 'content_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_sympal_content',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_content_comment', 'sf_sympal_content_comment_comment_id_sf_sympal_comment_id', array(
             'name' => 'sf_sympal_content_comment_comment_id_sf_sympal_comment_id',
             'local' => 'comment_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_sympal_comment',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_content_edit_group', 'sf_sympal_content_edit_group_content_id_sf_sympal_content_id', array(
             'name' => 'sf_sympal_content_edit_group_content_id_sf_sympal_content_id',
             'local' => 'content_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_sympal_content',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_content_edit_group', 'sf_sympal_content_edit_group_group_id_sf_guard_group_id', array(
             'name' => 'sf_sympal_content_edit_group_group_id_sf_guard_group_id',
             'local' => 'group_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_group',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_content_group', 'sf_sympal_content_group_content_id_sf_sympal_content_id', array(
             'name' => 'sf_sympal_content_group_content_id_sf_sympal_content_id',
             'local' => 'content_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_sympal_content',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_content_group', 'sf_sympal_content_group_group_id_sf_guard_group_id', array(
             'name' => 'sf_sympal_content_group_group_id_sf_guard_group_id',
             'local' => 'group_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_group',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_content_link', 'sf_sympal_content_link_content_id_sf_sympal_content_id', array(
             'name' => 'sf_sympal_content_link_content_id_sf_sympal_content_id',
             'local' => 'content_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_sympal_content',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_content_link', 'sf_sympal_content_link_linked_content_id_sf_sympal_content_id', array(
             'name' => 'sf_sympal_content_link_linked_content_id_sf_sympal_content_id',
             'local' => 'linked_content_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_sympal_content',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_content_list', 'sf_sympal_content_list_content_type_id_sf_sympal_content_type_id', array(
             'name' => 'sf_sympal_content_list_content_type_id_sf_sympal_content_type_id',
             'local' => 'content_type_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_sympal_content_type',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_content_list', 'sf_sympal_content_list_content_id_sf_sympal_content_id', array(
             'name' => 'sf_sympal_content_list_content_id_sf_sympal_content_id',
             'local' => 'content_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_sympal_content',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_content_slot_ref', 'scsi', array(
             'name' => 'scsi',
             'local' => 'content_slot_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_sympal_content_slot',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_content_slot_ref', 'sf_sympal_content_slot_ref_content_id_sf_sympal_content_id', array(
             'name' => 'sf_sympal_content_slot_ref_content_id_sf_sympal_content_id',
             'local' => 'content_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_sympal_content',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_content_tag', 'sf_sympal_content_tag_content_id_sf_sympal_content_id', array(
             'name' => 'sf_sympal_content_tag_content_id_sf_sympal_content_id',
             'local' => 'content_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_sympal_content',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_content_tag', 'sf_sympal_content_tag_tag_id_sf_sympal_tag_id', array(
             'name' => 'sf_sympal_content_tag_tag_id_sf_sympal_tag_id',
             'local' => 'tag_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_sympal_tag',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_menu_item', 'sf_sympal_menu_item_root_id_sf_sympal_menu_item_id', array(
             'name' => 'sf_sympal_menu_item_root_id_sf_sympal_menu_item_id',
             'local' => 'root_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_sympal_menu_item',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_menu_item', 'sf_sympal_menu_item_content_id_sf_sympal_content_id', array(
             'name' => 'sf_sympal_menu_item_content_id_sf_sympal_content_id',
             'local' => 'content_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_sympal_content',
             'onUpdate' => NULL,
             'onDelete' => 'SET NULL',
             ));
        $this->createForeignKey('sf_sympal_menu_item', 'sf_sympal_menu_item_site_id_sf_sympal_site_id', array(
             'name' => 'sf_sympal_menu_item_site_id_sf_sympal_site_id',
             'local' => 'site_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_sympal_site',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_menu_item_group', 'sf_sympal_menu_item_group_menu_item_id_sf_sympal_menu_item_id', array(
             'name' => 'sf_sympal_menu_item_group_menu_item_id_sf_sympal_menu_item_id',
             'local' => 'menu_item_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_sympal_menu_item',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_menu_item_group', 'sf_sympal_menu_item_group_group_id_sf_guard_group_id', array(
             'name' => 'sf_sympal_menu_item_group_group_id_sf_guard_group_id',
             'local' => 'group_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_group',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_page', 'sf_sympal_page_content_id_sf_sympal_content_id', array(
             'name' => 'sf_sympal_page_content_id_sf_sympal_content_id',
             'local' => 'content_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_sympal_content',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_plugin', 'sf_sympal_plugin_plugin_author_id_sf_sympal_plugin_author_id', array(
             'name' => 'sf_sympal_plugin_plugin_author_id_sf_sympal_plugin_author_id',
             'local' => 'plugin_author_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_sympal_plugin_author',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_redirect', 'sf_sympal_redirect_site_id_sf_sympal_site_id', array(
             'name' => 'sf_sympal_redirect_site_id_sf_sympal_site_id',
             'local' => 'site_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_sympal_site',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_sympal_redirect', 'sf_sympal_redirect_content_id_sf_sympal_content_id', array(
             'name' => 'sf_sympal_redirect_content_id_sf_sympal_content_id',
             'local' => 'content_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_sympal_content',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('sf_guard_forgot_password', 'sf_guard_forgot_password_user_id_sf_guard_user_id');
        $this->dropForeignKey('sf_guard_group_permission', 'sf_guard_group_permission_group_id_sf_guard_group_id');
        $this->dropForeignKey('sf_guard_group_permission', 'sf_guard_group_permission_permission_id_sf_guard_permission_id');
        $this->dropForeignKey('sf_guard_remember_key', 'sf_guard_remember_key_user_id_sf_guard_user_id');
        $this->dropForeignKey('sf_guard_user_group', 'sf_guard_user_group_user_id_sf_guard_user_id');
        $this->dropForeignKey('sf_guard_user_group', 'sf_guard_user_group_group_id_sf_guard_group_id');
        $this->dropForeignKey('sf_guard_user_permission', 'sf_guard_user_permission_user_id_sf_guard_user_id');
        $this->dropForeignKey('sf_guard_user_permission', 'sf_guard_user_permission_permission_id_sf_guard_permission_id');
        $this->dropForeignKey('sf_sympal_blog_post', 'sf_sympal_blog_post_content_id_sf_sympal_content_id');
        $this->dropForeignKey('sf_sympal_comment', 'sf_sympal_comment_user_id_sf_guard_user_id');
        $this->dropForeignKey('sf_sympal_content', 'sf_sympal_content_last_updated_by_id_sf_guard_user_id');
        $this->dropForeignKey('sf_sympal_content', 'sf_sympal_content_created_by_id_sf_guard_user_id');
        $this->dropForeignKey('sf_sympal_content', 'sf_sympal_content_site_id_sf_sympal_site_id');
        $this->dropForeignKey('sf_sympal_content', 'sf_sympal_content_content_type_id_sf_sympal_content_type_id');
        $this->dropForeignKey('sf_sympal_content_asset', 'sf_sympal_content_asset_content_id_sf_sympal_content_id');
        $this->dropForeignKey('sf_sympal_content_asset', 'sf_sympal_content_asset_asset_id_sf_sympal_asset_id');
        $this->dropForeignKey('sf_sympal_content_comment', 'sf_sympal_content_comment_content_id_sf_sympal_content_id');
        $this->dropForeignKey('sf_sympal_content_comment', 'sf_sympal_content_comment_comment_id_sf_sympal_comment_id');
        $this->dropForeignKey('sf_sympal_content_edit_group', 'sf_sympal_content_edit_group_content_id_sf_sympal_content_id');
        $this->dropForeignKey('sf_sympal_content_edit_group', 'sf_sympal_content_edit_group_group_id_sf_guard_group_id');
        $this->dropForeignKey('sf_sympal_content_group', 'sf_sympal_content_group_content_id_sf_sympal_content_id');
        $this->dropForeignKey('sf_sympal_content_group', 'sf_sympal_content_group_group_id_sf_guard_group_id');
        $this->dropForeignKey('sf_sympal_content_link', 'sf_sympal_content_link_content_id_sf_sympal_content_id');
        $this->dropForeignKey('sf_sympal_content_link', 'sf_sympal_content_link_linked_content_id_sf_sympal_content_id');
        $this->dropForeignKey('sf_sympal_content_list', 'sf_sympal_content_list_content_type_id_sf_sympal_content_type_id');
        $this->dropForeignKey('sf_sympal_content_list', 'sf_sympal_content_list_content_id_sf_sympal_content_id');
        $this->dropForeignKey('sf_sympal_content_slot_ref', 'scsi');
        $this->dropForeignKey('sf_sympal_content_slot_ref', 'sf_sympal_content_slot_ref_content_id_sf_sympal_content_id');
        $this->dropForeignKey('sf_sympal_content_tag', 'sf_sympal_content_tag_content_id_sf_sympal_content_id');
        $this->dropForeignKey('sf_sympal_content_tag', 'sf_sympal_content_tag_tag_id_sf_sympal_tag_id');
        $this->dropForeignKey('sf_sympal_menu_item', 'sf_sympal_menu_item_root_id_sf_sympal_menu_item_id');
        $this->dropForeignKey('sf_sympal_menu_item', 'sf_sympal_menu_item_content_id_sf_sympal_content_id');
        $this->dropForeignKey('sf_sympal_menu_item', 'sf_sympal_menu_item_site_id_sf_sympal_site_id');
        $this->dropForeignKey('sf_sympal_menu_item_group', 'sf_sympal_menu_item_group_menu_item_id_sf_sympal_menu_item_id');
        $this->dropForeignKey('sf_sympal_menu_item_group', 'sf_sympal_menu_item_group_group_id_sf_guard_group_id');
        $this->dropForeignKey('sf_sympal_page', 'sf_sympal_page_content_id_sf_sympal_content_id');
        $this->dropForeignKey('sf_sympal_plugin', 'sf_sympal_plugin_plugin_author_id_sf_sympal_plugin_author_id');
        $this->dropForeignKey('sf_sympal_redirect', 'sf_sympal_redirect_site_id_sf_sympal_site_id');
        $this->dropForeignKey('sf_sympal_redirect', 'sf_sympal_redirect_content_id_sf_sympal_content_id');
    }
}