<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addsfsympalcontenttype extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('sf_sympal_content_type', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'description' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'label' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'plugin_name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'default_path' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'theme' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'template' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'module' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'action' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
              'content_type_name' => 
              array(
              'fields' => 
              array(
               0 => 'name',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('sf_sympal_content_type');
    }
}