<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addsfsympalmenuitem extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('sf_sympal_menu_item', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'root_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'date_published' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'label' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'custom_path' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'requires_auth' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'requires_no_auth' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'html_attributes' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'site_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'content_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'lft' => 
             array(
              'type' => 'integer',
              'length' => 4,
             ),
             'rgt' => 
             array(
              'type' => 'integer',
              'length' => 4,
             ),
             'level' => 
             array(
              'type' => 'integer',
              'length' => 2,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('sf_sympal_menu_item');
    }
}