<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addsfsympalplugin extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('sf_sympal_plugin', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'plugin_author_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'description' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'summary' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'image' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'users' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'scm' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'homepage' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'ticketing' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'link' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'is_downloaded' => 
             array(
              'type' => 'boolean',
              'default' => 0,
              'length' => 25,
             ),
             'is_installed' => 
             array(
              'type' => 'boolean',
              'default' => 0,
              'length' => 25,
             ),
             'is_theme' => 
             array(
              'type' => 'boolean',
              'default' => 0,
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('sf_sympal_plugin');
    }
}